approvedGitRepositories:
  - "**"

enableScripts: true

packageExtensions:
  "@nuxt/devtools@*":
    peerDependencies:
      vue: "*"
  nuxt@*:
    peerDependencies:
      vite: "*"
  "@nuxt/test-utils@*":
    peerDependencies:
      vite: "*"
  vitest-environment-nuxt@*:
    peerDependencies:
      vite: "*"

nodeLinker: node-modules

npmMinimalAgeGate: 0
